### ISSUE TITLE
[BUG] <title> New version upgrade failed

### ISSUE THREAD

**Issue by Nctllnty** [apache/hertzbeat#2088]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

program cannot start

### Expected Behavior

update successed

### Steps To Reproduce

**Background**
1. Version 1.5 is deployed through helm;
**Steps**
1. Run sql upgrade (https://github.com/apache/hertzbeat/tree/master/manager/src/main/resources/db/migration/mysql);
2. Build a new image based on the official image
```
FROM tancloud/hertzbeat:v1.6.0
ADD https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-java-8.0.25.zip /opt/hertzbeat/ext-lib/
ADD https://download.oracle.com/otn-pub/otn_software/jdbc/234/ojdbc8.jar /opt/hertzbeat/ext-lib/
ADD https://repo.mavenlibs.com/maven/com/oracle/database/nls/orai18n/21.5.0.0/orai18n-21.5.0.0.jar?utm_source=mavenlibs.com /opt/hertzbeat/ext-lib/
RUN apt install -y unzip
RUN cd /opt/hertzbeat/ext-lib/ && unzip mysql-connector-java-8.0.25.zip
RUN cd /opt/hertzbeat/ext-lib/ && mv mysql-connector-java-8.0.25/mysql-connector-java-8.0.25.jar .
```
3. Update Deployment;

### Environment

```markdown
HertzBeat version(s):
```

### Debug logs

```
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# 
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# 
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# 
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# 
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# ls
apache-hertzbeat-1.6.0.jar  bin  config  define  DISCLAIMER  dist  ext-lib  lib  LICENSE  licenses  NOTICE  README.md
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# ./bin/
entrypoint.sh  restart.sh     shutdown.bat   shutdown.sh    startup.bat    startup.sh     
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# ./bin/entrypoint.sh 
-e Starting the HertzBeat apache-hertzbeat-1.6.0 ...
14:57:45,583 |-INFO in ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.4.14
14:57:45,587 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Here is a list of configurators discovered as a service, by rank: 
14:57:45,587 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 -   org.springframework.boot.logging.logback.RootLogLevelConfigurator
14:57:45,587 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - They will be invoked in order until ExecutionStatus.DO_NOT_INVOKE_NEXT_IF_ANY is returned.
14:57:45,587 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Constructed configurator of type class org.springframework.boot.logging.logback.RootLogLevelConfigurator
14:57:45,608 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - org.springframework.boot.logging.logback.RootLogLevelConfigurator.configure() call lasted 0 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
14:57:45,608 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Trying to configure with ch.qos.logback.classic.joran.SerializedModelConfigurator
14:57:45,609 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Constructed configurator of type class ch.qos.logback.classic.joran.SerializedModelConfigurator
14:57:45,612 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.scmo]
14:57:45,613 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.scmo]
14:57:45,613 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - ch.qos.logback.classic.joran.SerializedModelConfigurator.configure() call lasted 4 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
14:57:45,613 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Trying to configure with ch.qos.logback.classic.util.DefaultJoranConfigurator
14:57:45,614 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Constructed configurator of type class ch.qos.logback.classic.util.DefaultJoranConfigurator
14:57:45,614 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
14:57:45,615 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.xml]
14:57:45,615 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - ch.qos.logback.classic.util.DefaultJoranConfigurator.configure() call lasted 1 milliseconds. ExecutionStatus=INVOKE_NEXT_IF_ANY
14:57:45,615 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Trying to configure with ch.qos.logback.classic.BasicConfigurator
14:57:45,616 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - Constructed configurator of type class ch.qos.logback.classic.BasicConfigurator
14:57:45,616 |-INFO in ch.qos.logback.classic.BasicConfigurator@7bb3a9fe - Setting up default configuration.
14:57:45,638 |-INFO in ch.qos.logback.classic.util.ContextInitializer@611f8234 - ch.qos.logback.classic.BasicConfigurator.configure() call lasted 22 milliseconds. ExecutionStatus=NEUTRAL
14:57:46,354 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Registering a new ReconfigureOnChangeTask ReconfigureOnChangeTask(born:1718607466351)
14:57:46,354 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - No 'scanPeriod' specified. Defaulting to 1 minutes
14:57:46,354 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Will scan for changes in [file:/opt/hertzbeat/config/logback-spring.xml] 
14:57:46,354 |-INFO in ch.qos.logback.classic.model.processor.ConfigurationModelHandlerFull - Setting ReconfigureOnChangeTask scanning period to 1 minutes
14:57:46,360 |-WARN in ch.qos.logback.core.model.processor.AppenderModelHandler - Appender named [ConsoleAppender] not referenced. Skipping further processing.
14:57:46,360 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [SystemOutFileAppender]
14:57:46,360 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:57:46,394 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2092885124 - setting totalSizeCap to 5 GB
14:57:46,403 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2092885124 - Will use zip compression
14:57:46,404 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2092885124 - Will use the pattern logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-%d{yyyy-MM-dd}.%i.log for the active file
14:57:46,436 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7f811d00 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-%d{yyyy-MM-dd}.%i.log.zip'.
14:57:46,436 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7f811d00 - Roll-over at midnight.
14:57:46,445 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7f811d00 - Setting initial period to 2024-06-17T06:57:46.445Z
14:57:46,445 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7f811d00 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
14:57:46,445 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@7f811d00 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
14:57:46,448 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@2092885124 - Cleaning on start up
14:57:46,449 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
14:57:46,449 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
14:57:46,458 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
14:57:46,463 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SystemOutFileAppender] - Active log file name: logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-2024-06-17.0.log
14:57:46,464 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[SystemOutFileAppender] - File property is set to [null]
14:57:46,464 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [ErrOutFileAppender]
14:57:46,464 |-INFO in ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [ch.qos.logback.core.rolling.RollingFileAppender]
14:57:46,465 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1653751526 - setting totalSizeCap to 5 GB
14:57:46,465 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1653751526 - Will use zip compression
14:57:46,466 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1653751526 - Will use the pattern logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-%d{yyyy-MM-dd}-error.%i.log for the active file
14:57:46,466 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4089713 - The date pattern is 'yyyy-MM-dd' from file name pattern 'logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-%d{yyyy-MM-dd}-error.%i.log.zip'.
14:57:46,466 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4089713 - Roll-over at midnight.
14:57:46,467 |-INFO in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4089713 - Setting initial period to 2024-06-17T06:57:46.467Z
14:57:46,467 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4089713 - SizeAndTimeBasedFNATP is deprecated. Use SizeAndTimeBasedRollingPolicy instead
14:57:46,467 |-WARN in ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP@4089713 - For more information see http://logback.qos.ch/manual/appenders.html#SizeAndTimeBasedRollingPolicy
14:57:46,467 |-INFO in c.q.l.core.rolling.TimeBasedRollingPolicy@1653751526 - Cleaning on start up
14:57:46,468 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - first clean up after appender initialization
14:57:46,468 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Multiple periods, i.e. 32 periods, seem to have elapsed. This is expected at application start.
14:57:46,470 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ErrOutFileAppender] - Active log file name: logs/obs-hertzbeat-debug-6889fccdf5-kjpbn22-2024-06-17-error.0.log
14:57:46,470 |-INFO in ch.qos.logback.core.rolling.RollingFileAppender[ErrOutFileAppender] - File property is set to [null]
14:57:46,471 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.springframework] to INFO
14:57:46,471 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[org.springframework] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.json] to ERROR
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating ERROR level on Logger[org.json] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [io.netty] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[io.netty] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.slf4j] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[org.slf4j] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [ch.qos.logback] to WARN
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating WARN level on Logger[ch.qos.logback] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.kafka.clients] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[org.apache.kafka.clients] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.hibernate] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[org.hibernate] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.http] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[org.apache.http] onto the JUL framework
14:57:46,472 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.zaxxer] to INFO
14:57:46,472 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[com.zaxxer] onto the JUL framework
14:57:46,473 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [springfox] to INFO
14:57:46,473 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[springfox] onto the JUL framework
14:57:46,473 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.mongodb] to WARN
14:57:46,473 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating WARN level on Logger[org.mongodb] onto the JUL framework
14:57:46,473 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [io.greptime] to WARN
14:57:46,473 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating WARN level on Logger[io.greptime] onto the JUL framework
14:57:46,473 |-INFO in ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to INFO
14:57:46,473 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating INFO level on Logger[ROOT] onto the JUL framework
14:57:46,473 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [SystemOutFileAppender] to Logger[ROOT]
14:57:46,473 |-INFO in ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [ErrOutFileAppender] to Logger[ROOT]
14:57:46,473 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.obs.services.AbstractClient] to OFF
14:57:46,473 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating OFF level on Logger[com.obs.services.AbstractClient] onto the JUL framework
14:57:46,475 |-INFO in c.q.l.core.rolling.helper.TimeBasedArchiveRemover - Removed  0 Bytes of files
14:57:46,477 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.obs.services.AbstractClient] to false
14:57:46,477 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.obs.services.internal.RestStorageService] to OFF
14:57:46,477 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating OFF level on Logger[com.obs.services.internal.RestStorageService] onto the JUL framework
14:57:46,477 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.obs.services.internal.RestStorageService] to false
14:57:46,477 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [com.obs.log.AccessLogger] to OFF
14:57:46,477 |-INFO in ch.qos.logback.classic.jul.LevelChangePropagator@f19c9d2 - Propagating OFF level on Logger[com.obs.log.AccessLogger] onto the JUL framework
14:57:46,477 |-INFO in ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [com.obs.log.AccessLogger] to false
14:57:46,477 |-INFO in ch.qos.logback.core.model.processor.DefaultProcessor@7807ac2c - End of configuration.
14:57:46,477 |-INFO in org.springframework.boot.logging.logback.SpringBootJoranConfigurator@b91d8c4 - Registering current configuration as safe fallback point

  _   _           _       ____             _
 | | | | ___ _ __| |_ ___| __ )  ___  __ _| |_
 | |_| |/ _ \ '__| __|_  /  _ \ / _ \/ _` | __|        Profile: prod
 |  _  |  __/ |  | |_ / /| |_) |  __/ (_| | |_         Name: obs-hertzbeat-debug-6889fccdf5-kjpbn22 Port: 1157 Pid: 22
 |_| |_|\___|_|   \__/___|____/ \___|\__,_|\__|        https://hertzbeat.apache.org/ 

root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# ls
apache-hertzbeat-1.6.0.jar  bin  config  define  DISCLAIMER  dist  ext-lib  lib  LICENSE  licenses  logs  NOTICE  README.md
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat# cd logs/
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat/logs# ls
obs-hertzbeat-debug-6889fccdf5-kjpbn22-2024-06-17.0.log  obs-hertzbeat-debug-6889fccdf5-kjpbn22-2024-06-17-error.0.log
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat/logs# cat obs-hertzbeat-debug-6889fccdf5-kjpbn22-2024-06-17.0.log 
2024-06-17 14:57:46.570 [main] INFO  org.apache.hertzbeat.manager.Manager Line:50  - Starting Manager v2.0-SNAPSHOT using Java 17.0.2 with PID 22 (/opt/hertzbeat/apache-hertzbeat-1.6.0.jar started by root in /opt/hertzbeat)
2024-06-17 14:57:46.572 [main] INFO  org.apache.hertzbeat.manager.Manager Line:660 - The following 1 profile is active: "prod"
2024-06-17 14:57:48.145 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate Line:139 - Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2024-06-17 14:57:48.454 [main] INFO  org.springframework.data.repository.config.RepositoryConfigurationDelegate Line:208 - Finished Spring Data repository scanning in 300 ms. Found 24 JPA repository interfaces.
2024-06-17 14:57:49.926 [main] INFO  org.springframework.boot.web.embedded.tomcat.TomcatWebServer Line:109 - Tomcat initialized with port 1157 (http)
2024-06-17 14:57:49.937 [main] INFO  org.apache.coyote.http11.Http11NioProtocol Line:173 - Initializing ProtocolHandler ["http-nio-1157"]
2024-06-17 14:57:49.939 [main] INFO  org.apache.catalina.core.StandardService Line:173 - Starting service [Tomcat]
2024-06-17 14:57:49.940 [main] INFO  org.apache.catalina.core.StandardEngine Line:173 - Starting Servlet engine: [Apache Tomcat/10.1.19]
2024-06-17 14:57:50.021 [main] INFO  org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] Line:173 - Initializing Spring embedded WebApplicationContext
2024-06-17 14:57:50.022 [main] INFO  org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext Line:296 - Root WebApplicationContext: initialization completed in 3371 ms
2024-06-17 14:57:50.136 [main] INFO  com.usthe.sureness.configuration.SurenessAutoConfiguration Line:195 - [sureness-starter] - SurenessSubjectFactory init success
2024-06-17 14:57:50.621 [main] INFO  com.usthe.sureness.configuration.SurenessJakartaServletFilter Line:50  - servlet surenessFilter initialized
2024-06-17 14:57:50.895 [main] INFO  com.zaxxer.hikari.HikariDataSource Line:110 - HikariPool-1 - Starting...
2024-06-17 14:57:51.337 [main] INFO  com.zaxxer.hikari.pool.HikariPool Line:565 - HikariPool-1 - Added connection com.mysql.cj.jdbc.ConnectionImpl@22decfa2
2024-06-17 14:57:51.339 [main] INFO  com.zaxxer.hikari.HikariDataSource Line:123 - HikariPool-1 - Start completed.
2024-06-17 14:57:51.397 [main] INFO  org.flywaydb.core.FlywayExecutor Line:41  - Database: jdbc:mysql://obs-hertzbeat-database:3306/hertzbeat (MySQL 8.4)
2024-06-17 14:57:51.410 [main] WARN  org.flywaydb.core.internal.database.base.Database Line:45  - Flyway upgrade recommended: MySQL 8.4 is newer than this version of Flyway and support has not been tested. The latest supported version of MySQL is 8.1.
2024-06-17 14:57:51.439 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext Line:632 - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Found more than one migration with version 160
Offenders:
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/h2/V160__update_column.sql (SQL)
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/mysql/V160__update_column.sql (SQL)
2024-06-17 14:57:51.440 [main] INFO  com.zaxxer.hikari.HikariDataSource Line:350 - HikariPool-1 - Shutdown initiated...
2024-06-17 14:57:51.457 [main] INFO  com.zaxxer.hikari.HikariDataSource Line:352 - HikariPool-1 - Shutdown completed.
2024-06-17 14:57:51.461 [main] INFO  org.apache.catalina.core.StandardService Line:173 - Stopping service [Tomcat]
2024-06-17 14:57:51.462 [main] INFO  com.usthe.sureness.configuration.SurenessJakartaServletFilter Line:55  - servlet surenessFilter destroyed
2024-06-17 14:57:51.482 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger Line:82  - 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-06-17 14:57:51.498 [main] ERROR org.springframework.boot.SpringApplication Line:851 - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Found more than one migration with version 160
Offenders:
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/h2/V160__update_column.sql (SQL)
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/mysql/V160__update_column.sql (SQL)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:600)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:522)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1231)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:949)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:334)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.apache.hertzbeat.manager.Manager.main(Manager.java:44)
Caused by: org.flywaydb.core.api.FlywayException: Found more than one migration with version 160
Offenders:
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/h2/V160__update_column.sql (SQL)
-> /opt/hertzbeat/file:/opt/hertzbeat/apache-hertzbeat-1.6.0.jar!/db/migration/mysql/V160__update_column.sql (SQL)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.checkForIncompatibilities(CompositeMigrationResolver.java:94)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:127)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:114)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:120)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:86)
        at org.flywaydb.core.internal.command.DbValidate.lambda$validate$0(DbValidate.java:112)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:59)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:105)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:418)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:162)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:209)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:151)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1833)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
        ... 18 common frames omitted
root@obs-hertzbeat-debug-6889fccdf5-kjpbn:/opt/hertzbeat/logs# 
```

**Comment by Nctllnty** [comment]
<img width="1150" alt="image" src="https://github.com/apache/hertzbeat/assets/33241818/ff89c862-2b01-4be6-abaa-778fb1f60906">
Why is there no syntax for updating the table structure in the SQL statement of MySQL migration?
