### ISSUE TITLE
[BUG] monitoring k8s error

### ISSUE THREAD

**Issue by MrFrankBolt** [apache/hertzbeat#2096]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

按照文档生成了对应的k8s认证token，然后监控集群，发现一直处于宕机状态，观察后端log发现如下：
![e3f7d3b3c217f7810ff18c770f2ec4ac](https://github.com/apache/hertzbeat/assets/120542351/34752a3e-f140-4891-ab59-f99feb14868c)

### Expected Behavior

希望可以正常监控k8s，采集对应的指标

### Steps To Reproduce

1. 使用的是1.6.0镜像版本，之前是在1.4.4版本，按照文档进行了升级；
2. 配置只做了数据源相关的更改，其他都是原始默认，k8s采集yaml也是使用的默认；
3. 使用docker启动；
4. 查看k8s监控结果，出现上述描述异常；

### Environment

```markdown
HertzBeat version(s):v1.6.0
```

### Debug logs

2024-06-19 17:01:09.893 [339555282159616-kubernetes-nodes-9839] ERROR org.apache.hertzbeat.collector.dispatch.WorkerPool Line:48  - Thread Name 339555282159616-kubernetes-nodes-9839 : Character K is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
java.lang.NumberFormatException: Character K is neither a decimal digit number, decimal point, nor "e" notation exponential mark.
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:582)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:467)
        at java.base/java.math.BigDecimal.<init>(BigDecimal.java:896)
        at org.apache.hertzbeat.collector.dispatch.unit.impl.DataSizeConvert.convert(DataSizeConvert.java:46)
        at org.apache.hertzbeat.collector.dispatch.MetricsCollect.calculateFields(MetricsCollect.java:310)
        at org.apache.hertzbeat.collector.dispatch.MetricsCollect.run(MetricsCollect.java:176)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ncuhe** [comment]
<img width="1136" alt="1725165814751" src="https://github.com/user-attachments/assets/3a5adb92-cd25-45ae-b1a4-264669d959f2">
