### ISSUE TITLE
[BUG] <title>AlarmCommonReduce throw exception `UnsupportedOperationException`

### ISSUE THREAD

**Issue by yuluo-yx** [apache/hertzbeat#2411]
```java
    public void reduceAndSendAlarm(Alert alert) {
        alert.setTimes(1);
        Map<String, String> tags = alert.getTags();
        if (tags == null) {
            tags = new HashMap<>(8);
            alert.setTags(tags);
        }

        System.out.println("确认 tag 是否可以修改：");
        System.out.println("原有 tags + " + tags);
        System.out.println("===========================");
        System.out.println("tags 添加值 1 1 ：");
        tags.put("1", "1");
        System.out.println("===========================");
        System.out.println("测试结束");


        String monitorIdStr = tags.get(CommonConstants.TAG_MONITOR_ID);
        if (monitorIdStr == null) {
            log.debug("receiver extern alarm message: {}", alert);
        } else {
```

output:

```
Java HotSpot(TM) 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
确认 tag 是否可以修改：
原有 tags + {monitorId=123}
===========================
tags 添加值 1 1 ：

java.lang.UnsupportedOperationException
	at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.put(ImmutableCollections.java:1072)
	at org.apache.hertzbeat.alert.reduce.AlarmCommonReduce.reduceAndSendAlarm(AlarmCommonReduce.java:60)
	at org.apache.hertzbeat.alert.reduce.AlarmCommonReduceTest.testReduceAndSendAlarmWithMonitorId(AlarmCommonReduceTest.java:108)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by yuluo-yx** [comment]
![image](https://github.com/user-attachments/assets/72c1c3f4-a9af-41b5-847b-1dd6bcaf6a1d)

this issue from lombok `@Data` generated `setter` method. it is immutable collection
